version: "3.2"

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:7.6.2
    volumes:
      - /etc/docker/shared/artifactory:/var/opt/jfrog/artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx1024m -Xss256k -XX:+UseG1GC"

networks:
  default:
    external:
      name: default_network
