version: "3.2"

services:
  mongo:
    image: mongo
    volumes:
      - /etc/docker/shared/mongo/db:/data/db
    deploy:
      replicas: 1
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27017:27017"

networks:
  default:
    external:
      name: default_network
