version: "3.2"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /etc/docker/shared/prometheus:/prometheus
    deploy:
      replicas: 1
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    user: "1000:1000"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - /etc/docker/shared/grafana:/var/lib/grafana
    deploy:
      replicas: 1
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    user: "472:1"

networks:
  default:
    external:
      name: default_network
