version: "3.2"

services:
  docker-reverse-proxy-1:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    env_file:
      - ./.env-reverse-docker

  docker-reverse-proxy-2:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    env_file:
      - ./.env-reverse-docker

  docker-load-balancer:
    image: nginx
    volumes:
      - ./docker-load-balancer.conf:/etc/nginx/nginx.conf
    deploy:
      replicas: 1
    depends_on:
      - docker-reverse-proxy-1
      - docker-reverse-proxy-2
      # - docker-reverse-proxy-3

  registry-reverse-proxy:
    image: nginx
    volumes:
      - ./registry-reverse-proxy.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:25000"
    deploy:
      placement:
        constraints:
          - "node.role==manager"

networks:
  default:
    external:
      name: default_network
