# Global configuration
# We can override most of its property for specific job
# Using the same property

global:

  # How frequently to scrape targets by default
  scrape_interval: 15s

  # How long until a scrape request times out
  scrape_timeout: 10s

# A list of scrape configurations
#
# The job name assigned to scraped metrics by default
# Must be unique
# job_name: <job_name>
# 
# The HTTP resource path on which to fetch metrics from targets
# [ metrics_path: <path> | default = /metrics ]
# 
# List of labeled statically configured targets for this job.
# static_configs:
# 
#   # The targets specified by the static config.
#   targets:
#     [ - '<host>' ]

scrape_configs:

  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'services-collecting'

    metrics_path: '/actuator/prometheus'

    dns_sd_configs:
      - names:
          - 'tasks.demo-service'
          - 'tasks.am-parser-service'
          - 'tasks.simple-parser-service'
          - 'tasks.winestyle-parser-service'
          - 'tasks.winelab-parser-service'
          - 'tasks.lenta-parser-service'
          - 'tasks.crossroad-parser-service'
          - 'tasks.user-service'
          - 'tasks.notification-service'
          - 'tasks.catalog-service'
          - 'tasks.deployment-service'
          - 'tasks.recommendation-service'
          - 'tasks.api-gateway'
        type: 'A'
        port: 8080


# Official Documentation:
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
